[package]
name = "acid64c"
version = "1.0.8"
authors = ["Wilfred Bos"]
description = "ACID64 Console SID player."
readme = "README.md"
edition = "2021"
license = "GPL-3.0-or-later"
keywords = ["ACID64 console player", "sidplayer", "c64 music player", "SID 6581", "SID 8580"]
build = "build.rs"

[dependencies]
attohttpc = { version = "0.24", features = ["multipart-form"] }
chrono = "0.4"
crossterm = "0.26"
encoding = "0.2"
if-addrs = "0.9"
libloading = "0.7"
parking_lot = "0.12"
timer = "0.2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
ProductName = "ACID64 Console Player"
LegalCopyright = "Copyright © 2003 - 2023 Wilfred Bos"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
