[package]
name = "acid64c"
version = "1.0.8"
authors = ["Wilfred Bos"]
description = "ACID64 Console SID player."
readme = "README.md"
edition = "2021"
license = "GPL-3.0-or-later"
keywords = ["ACID64 console player", "sidplayer", "c64 music player", "SID 6581", "SID 8580"]
build = "build.rs"

[dependencies]
atomicring = "1.2.9"
attohttpc = { version = "0.25", features = ["multipart-form"] }
chrono = "0.4"
crossterm = "0.26"
encoding = "0.2"
encoding_rs = "0.8.32"
encoding_rs_io = "0.1.7"
if-addrs = "0.10"
libloading = "0.8"
parking_lot = "0.12"
timer = "0.2"
thread-priority = "0.13.1"

[dependencies.libftd2xx]
version = "0.32.2"
features = ["static"]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48.0", features = [
    "Win32_Media"
] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
ProductName = "ACID64 Console Player"
LegalCopyright = "Copyright © 2003 - 2023 Wilfred Bos"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
